version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ahmedmasmoudi047/django-backend:v20250726015323
    container_name: django-backend
    ports:
      - "8000:8000"
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_HOST: db
    depends_on:
      - db

  frontend:
    image: ahmedmasmoudi047/react-frontend:v20250726015323
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
